apiVersion: apps/v1
kind: Deployment
metadata:
  name: memberservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memberservice
  template:
    metadata:
      labels:
        app: memberservice
    spec:
      containers:
        - name: memberservice
          image: your-dockerhub-username/memberservice
          ports:
            - containerPort: 0 # This is a placeholder port
          env:
            - name: EUREKA_SERVER_URL
              value: http://eureka-server:8761/eureka/
