apiVersion: apps/v1
kind: Deployment
metadata:
  name: discoveryservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discoveryservice
  template:
    metadata:
      labels:
        app: discoveryservice
    spec:
      containers:
        - name: discoveryservice
          image: your-dockerhub-username/discoveryservice
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: discoveryservice
spec:
  selector:
    app: discoveryservice
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
