apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: your-dockerhub-username/orderservice
          ports:
            - containerPort: 0 # This is a placeholder port
          env:
            - name: EUREKA_SERVER_URL
              value: http://eureka-server:8761/eureka/
